### ISSUE TITLE
noop puppet run returns that we have to apply again

### ISSUE THREAD

**Issue by vmpr** [site24x7/puppet-site24x7#2]
Hi,

we have puppet in combination with foreman running and puppet runs at default with "noop" option, so it doesn`t apply all changes instantly.

The Problem is, foreman says all the time, that there "pending changes" because there is no test, that says "all is okay", have a look:

puppet agent --test --noop 
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for SERVERNAME
Info: Applying configuration version '1476471034'
Notice: /Stage[main]/Site24x7::Linuxagent/Exec[remove_tmp_directory]/returns: current_value notrun, should be 0 (noop)
Notice: /Stage[main]/Site24x7/Notify[site24x7 linux monitoring agent installation completed]/message: current_value absent, should be site24x7 linux monitoring agent installation completed (noop)
Notice: /Stage[main]/Site24x7::Linuxagent/Notify[Proxy Info  : proxy:3128]/message: current_value absent, should be Proxy Info  : proxy:3128 (noop)
Notice: /Stage[main]/Site24x7::Linuxagent/Notify[File To Download : Site24x7_Linux_64bit.install]/message: current_value absent, should be File To Download : Site24x7_Linux_64bit.install (noop)
Notice: /Stage[main]/Site24x7::Linuxagent/Notify[Succesully Completed]/message: current_value absent, should be Succesully Completed (noop)
Notice: /Stage[main]/Site24x7/Notify[site24x7 linux monitoring agent installation started]/message: current_value absent, should be site24x7 linux monitoring agent installation started (noop)
Notice: Class[Site24x7]: Would have triggered 'refresh' from 2 events
Notice: /Stage[main]/Site24x7::Linuxagent/Notify[OS Architecture : x86_64]/message: current_value absent, should be OS Architecture : x86_64 (noop)
Notice: /Stage[main]/Site24x7::Linuxagent/Notify[DEVICE KEY  : XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX]/message: current_value absent, should be DEVICE KEY  : XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX (noop)
Notice: Class[Site24x7::Linuxagent]: Would have triggered 'refresh' from 6 events
Notice: Stage[main]: Would have triggered 'refresh' from 2 events
Notice: Finished catalog run in 0.49 seconds

Is it possible to build in an better result for noop-runs?

Thank you!
Ringo

**Comment by vmpr** [comment]
no response? :(

**Comment by davividal** [comment]
If I'm not mistaken, the issue are due to the `notify` blocks.

**Comment by site24x7** [comment]
Hello vmpr,Our apologies for the delay in getting back to you. Thanks for the suggestion we have handled the 'x86_64' type for the 'os_arch' command.Regards,Magesh RajanSite24x7 Team | ZOHO CorpPhone: +1 408 352 9117 | +44 203 564 78934141 Hacienda Dr, Pleasanton, CA 94588, USA---- On Fri, 2 Dec 2016 11:43:35 +0530 notifications@github.com  wrote ---- no response? :(  —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by site24x7-old** [comment]
Hi vmpr,

As @davividal  suggested the issue is due to the wrong handling of notify blocks . Now we have updated the puppet scripts to provide proper results.
