### ISSUE TITLE
$os_arch needs more possibilities

### ISSUE THREAD

**Issue by vmpr** [site24x7/puppet-site24x7#3]
Hi,

we had the problem, that the installer tried to install all the time the 32bit File, because our System ist not amd64, it is x86_64. We`ve changed it in our environment and now it works for us, maybe you can add it to your code. 

if $os_arch=="amd64"
{
$install_file="Site24x7_Linux_64bit.install"
}
else
{
$install_file="Site24x7_Linux_32bit.install"
}

Thanks!
Ringo

**Comment by vmpr** [comment]
no response? :(

**Comment by site24x7-old** [comment]
Hi vmpr,

Thanks for the suggestion and apologies for the delayed response.

Right now the 'x86_64' type is also handled for the 'os_arch' command.
